---
title: "Shiny Optimization"
output: html_notebook
---

In this notebook I'll show some techniques that I use to optimize my shiny apps
to the point that I can upload them to a free 1GB RAM server (shinyapps.io)

#Find what is slow in your code:

Starting the process of optimization on an app can be quite rewarding if you start by the chunks of code that take more time to be processed. This is called collecting the low hanging fruits and can be easily achieved using the right tools.

I'm going to pick an [app](https://github.com/raylandmagalhaes/Densidade_Gastos_Deputados) that I'm currently working on and needs improvement, but you can choose the one you want to optimize.

We are going to use the funcion profviz that will show how much memory and how much time each chunk of code takes to run. 


```{r}
library(profvis)
library(shiny)

#Uncoment and run

#After your app pops up, play with it and make it work so that the function can capture how much time each task take to run.

# Initial_Profile <- profvis(runApp(appDir="app.R"))

# Initial_Profile
# htmlwidgets::saveWidget(Initial_Profile, "Initial_Profile.html")

```

Looking at our [Initial profile,](./Initial_Profile.html) we can see that our App takes 5930ms to initialize, 630ms to run the output$densidades for the first time and 2480ms for the second.
What we can also see is that it took 2670.7MB of RAM to initialize, wich by itself would turn our dream to upload it on a free server into ashes.

Starting the optimization with the optimization with the initialization seems to be our best choice in this situation, so lets get started.

